document.getElementById('deck').insertAdjacentHTML('beforeend', String.raw`
<section class="slide center" data-kind="main" data-note-key="m27"><div class="slidehead"><div class="eyebrow">Act 4 · Optimization ceiling?</div><h2>Does extensibility force us into “local plugins forever”?</h2></div><div class="panel broken"><p class="bigq">modules → opaque boundaries → local optimization only?</p></div><p class="caption">That outcome is possible — but it is not required by the design.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m28"><div class="slidehead"><div class="eyebrow">Two different times</div><h2>Extensibility can exist mostly during authoring and planning</h2></div><div class="timeline"><div><b>AUTHOR</b><span>independent modules</span></div><i>→</i><div><b>COMPOSE</b><span>resolve dependencies / policy</span></div><i>→</i><div class="good"><b>FREEZE</b><span>one concrete compiler</span></div><i>→</i><div><b>OPTIMIZE</b><span>whole IR / global analyses</span></div></div></section>
<section class="slide two" data-kind="main" data-note-key="m29"><div class="slidehead"><div class="eyebrow">Design objective</div><h2>Module boundaries should not become permanent optimization boundaries</h2></div><div class="panel good"><h3>After resolution</h3><p>one route<br/>concrete representations<br/>known passes<br/>known backend</p></div><div class="panel"><h3>Then</h3><p class="bigq">global analyses and optimizations can see the unified IR they need.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m30"><div class="slidehead"><div class="eyebrow">Design sketch · high-level intent</div><h2>Users should be able to request policy, not spell every prerequisite</h2></div><div class="panel code bigcode">optimization aggressive</div><div class="panel"><span class="boundary hypothesis">DESIGN SKETCH</span><p>May imply canonicalization, SSA-like form, legalization, analysis prerequisites and target-specific choices.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m31"><div class="slidehead"><div class="eyebrow">Analogy · LLVM</div><h2>Optimization level is already a high-level request for a derived pass pipeline</h2></div><div class="panel"><span class="boundary analogy">ANALOGY</span><p class="bigq"><code>OptimizationLevel::O2/O3</code></p><p>LLVM PassBuilder constructs default optimization pipelines and exposes extension points.</p></div><div class="panel"><p>Useful intuition: high-level policy → concrete pass pipeline.</p><p class="caption">Not a claim that UT reproduces LLVM’s exact O3 pipeline.</p></div><div class="sourcebar"><a href="https://llvm.org/docs/NewPassManager.html" rel="noreferrer" target="_blank">LLVM New Pass Manager</a><a href="https://llvm.org/docs/WritingAnLLVMNewPMPass.html" rel="noreferrer" target="_blank">LLVM pass plugins</a></div></section>
<section class="slide stack" data-kind="main" data-note-key="m32"><div class="slidehead"><div class="eyebrow">Why high-level intent creates planning work</div><h2>An optimization may require a representation property first</h2></div><div class="pipeline"><div>aggressive policy</div><i>→</i><div class="hard">needs property P</div><i>→</i><div>choose conversion / legalization</div><i>→</i><div>run optimization</div><i>→</i><div>backend</div></div><p class="caption centertext"><span class="boundary hypothesis">HYPOTHETICAL EXAMPLE</span> P could be SSA-like form, normalized layout, target legality, etc.</p></section>
<section class="slide two" data-kind="main" data-note-key="m33"><div class="slidehead"><div class="eyebrow">Implementation lesson · fixed in current UT</div><h2>Choosing the cheapest conversion skeleton too early was wrong</h2></div><div class="panel broken"><h3>Historical failure</h3><p>pick cheapest conversion topology<br/>then place mandatory pass<br/>→ globally feasible route can be missed</p></div><div class="panel good"><span class="boundary current">CURRENT UT: FIXED</span><p>Route search now includes mandatory-pass coverage before preference.</p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/research/planner-iterative-repair-status-2026-09-03.md" rel="noreferrer" target="_blank">Planner repair status</a></div></section>
<section class="slide center" data-kind="main" data-note-key="m34"><div class="slidehead"><div class="eyebrow">The planning rule that survived the bug fix</div><h2><span class="accent">FEASIBILITY FIRST.</span><br/>PREFERENCE SECOND.</h2></div><div class="decisionrule"><div class="good"><b>hard constraints</b><span>semantic feasibility · mandatory constraints · explicit ambiguity handling</span></div><div><b>preferences</b><span>Cost · Order · policy among feasible candidates</span></div></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/research/planner-iterative-repair-status-2026-09-03.md" rel="noreferrer" target="_blank">Planner repair status</a></div></section>
<section class="slide two" data-kind="main" data-note-key="m35"><div class="slidehead"><div class="eyebrow">Current implementation boundary</div><h2>Route Cost is still a preference signal — not a proof of meaning</h2></div><div class="panel code">LanguageArtifactRouteStep(..., int Cost)

LanguageArtifactRoute.TotalCost : long</div><div class="panel"><span class="boundary current">CURRENT UT</span><p>Typed artifact contracts + mandatory-pass feasibility are checked.</p><p class="caption">But cost does not prove semantic preservation, trust, or cross-level meaning.</p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/UniversalToolchain/UniversalToolchain.LanguageSdk/LanguagePlan.cs" rel="noreferrer" target="_blank">LanguagePlan.cs</a><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/research/planner-iterative-repair-status-2026-09-03.md" rel="noreferrer" target="_blank">Planner repair status</a></div></section>
<section class="slide two" data-kind="main" data-note-key="m36"><div class="slidehead"><div class="eyebrow">Why preference can never replace requirements</div><h2>A cheaper route may destroy an opportunity we explicitly care about</h2></div><div class="panel broken"><h3>Route A · cost 2</h3><p>reaches backend<br/><b>but lacks property P</b><br/>optimization unavailable</p></div><div class="panel good"><h3>Route B · cost 4</h3><p>passes through required form<br/><b>property P available</b><br/>optimization legal</p></div><p class="caption span2 centertext"><span class="boundary hypothesis">HYPOTHETICAL EXAMPLE</span> Requirements determine admissibility; preference ranks admissible plans.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m37"><div class="slidehead"><div class="eyebrow">Title payoff · first half</div><h2>Deep abstractions for authoring → one concrete compiler for optimization</h2></div><div class="mapflow horizontal"><div>MODULES</div><i>→</i><div>CONFIG</div><i>→</i><div>PLANNER</div><i>→</i><div class="good">FROZEN PLAN</div><i>→</i><div>UNIFIED IR</div><i>→</i><div>GLOBAL OPTIMIZATION</div></div><p class="bigq centertext">Make composition explicit — then stop paying for ambiguity.</p></section>
`);
