document.getElementById('deck').insertAdjacentHTML('beforeend', String.raw`
<section class="slide stack" data-kind="main" data-note-key="m9"><div class="slidehead"><div class="eyebrow">Act 2 · Build from modules</div><h2>Three terms: Wist module, Feature, Contribution</h2></div><div class="taxonomy"><div class="tax-node module"><span class="tax-kicker">Wist-facing selection</span><b>Wist module alias</b><span>selectable extension unit such as <code>Arithmetic</code> or <code>Scopes</code></span></div><div class="tax-link"><span>requests</span><i>→</i></div><div class="tax-node feature"><span class="tax-kicker">generic capability</span><b>Feature</b><span>requested in a <code>LanguageDefinition</code></span></div><div class="tax-link reverse"><i>←</i><span>provided by</span></div><div class="tax-node contribution"><span class="tax-kicker">implementation participant</span><b>Contribution</b><span>syntax owner · pass · conversion · backend · tooling…</span></div></div><p class="caption centertext">Optimizers and backends are ecosystem component categories too; they are not all “Wist modules”.</p><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/write-modules/index.md" rel="noreferrer" target="_blank">Wist module authoring</a><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/start/mental-model.md" rel="noreferrer" target="_blank">Generic mental model</a></div></section>
<section class="slide two" data-kind="main" data-note-key="m10"><div class="slidehead"><div class="eyebrow">Independent development</div><h2>Two extension authors should not need a private handshake</h2></div><div class="panel"><h3>Developer A</h3><p>authors a type / refinement feature</p></div><div class="panel"><h3>Developer B</h3><p>authors an array bounds checker</p></div><p class="bigq span2 centertext">First goal: both can join the ecosystem without knowing each other.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m11"><div class="slidehead"><div class="eyebrow">One ecosystem, multiple languages</div><h2>The same ecosystem can produce different language profiles</h2></div><div class="profile-compose"><div class="profile-lane"><div class="profile-name"><b>dialect A</b><span>tiny arithmetic</span></div><div class="profile-chips"><span>Arithmetic module</span><span>Numbers module</span><span class="shared">Scopes module</span><span class="shared">Interpreter backend</span></div></div><div class="profile-lane"><div class="profile-name"><b>dialect B</b><span>restricted pricing</span></div><div class="profile-chips"><span class="shared">Scopes module</span><span>Variables module</span><span>optimizer</span><span>CIL backend</span><span class="shared">Interpreter backend</span></div></div><div class="profile-lane"><div class="profile-name"><b>dialect C</b><span>full profile</span></div><div class="profile-chips"><span>Arithmetic module</span><span>Numbers module</span><span class="shared">Scopes module</span><span>Variables module</span><span>optimizer</span><span>CIL backend</span><span class="shared">Interpreter backend</span></div></div></div><p class="caption centertext">A profile composes several component categories; repeated bricks make reuse visible, and “module” is not the name of every brick.</p></section>
<section class="slide two" data-kind="main" data-note-key="m12"><div class="slidehead"><div class="eyebrow">Terminology boundary</div><h2>Here “dialect” means <span class="accent">language profile / configuration</span></h2></div><div class="panel good"><h3>Wist .wistdialect</h3><p>selects modules, optimizers, policy and backends</p></div><div class="panel broken"><h3>Not MLIR dialect</h3><p>MLIR dialects define IR operations/types/attributes at abstraction levels</p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/build-dsls/dialect-files.md" rel="noreferrer" target="_blank">Wist dialect docs</a><a href="https://mlir.llvm.org/docs/Dialects/" rel="noreferrer" target="_blank">MLIR dialects</a></div></section>
<section class="slide two" data-kind="main" data-note-key="m13"><div class="slidehead"><div class="eyebrow">Current implementation · real profile</div><h2>This profile requests four Wist module aliases</h2></div><div class="panel code bigcode">dialect MinimalArithmetic
use Arithmetic,Numbers,Scopes,Whitespaces
backend interpreter</div><div class="panel"><span class="boundary current">CURRENT UT</span><p class="bigq">Executable configuration, not pseudocode.</p><p>Dependency closure may add required features/contributions beyond the aliases written here.</p><p>Example: <code>2 + 3 * 4</code> → <code>14</code>.</p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/UniversalToolchain/Dialects/examples/wist/minimal-arithmetic/dialect.wistdialect" rel="noreferrer" target="_blank">MinimalArithmetic</a><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/docs/reference/dialect-reference.md" rel="noreferrer" target="_blank">Dialect reference</a></div></section>
<section class="slide two" data-kind="main" data-note-key="m14"><div class="slidehead"><div class="eyebrow">Current implementation · richer profile</div><h2>The same configuration language scales to a fuller Wist profile</h2></div><div class="panel code compactcode">dialect FullDefault
use Arithmetic,BooleanConditions,Comments,
    ComparisonConditions,Conditions,CSharpInterop,
    Equality,Identifier,Labels,Loops,Numbers,
    Scopes,SemicolonAsNewLine,Variables,Whitespaces
backend cil,interpreter
enable BooleanOptimization
enable ComparisonIntrinsicOptimization
security trusted
capability unsafe-interop</div><div class="panel"><span class="boundary current">CURRENT UT</span><p>More language surface, two backends, optimizer selections and policy.</p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/UniversalToolchain/Dialects/examples/wist/full-default/dialect.wistdialect" rel="noreferrer" target="_blank">FullDefault</a></div></section>
<section class="slide two" data-kind="main" data-note-key="m15"><div class="slidehead"><div class="eyebrow">Current implementation · policy profile</div><h2>A dialect can also make the language deliberately smaller</h2></div><div class="panel code compactcode">dialect PricingRestricted
use Identifier,NativeTypes,Scopes,Variables,Whitespaces
exclude Arithmetic,...,CSharpInterop,...,Loops,...
backend cil,interpreter
enable ArithmeticOptimization
enable EGraphOptimization
enable NativeCilOptimization
enable NativeTypesOptimization
security restricted</div><div class="panel"><span class="boundary current">CURRENT UT</span><p class="bigq">Extensibility also includes explicit constraints and policy.</p><p class="caption"><code>exclude</code> marks contributions unavailable in this definition; it is not base-profile subtraction or inheritance. Restricted composition ≠ process isolation.</p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/1078ddb5b9fd83b569a8ef0e590c4bec9594e1c5/UniversalToolchain/Dialects/examples/wist/pricing-restricted/dialect.wistdialect" rel="noreferrer" target="_blank">PricingRestricted</a></div></section>
<section class="slide center" data-kind="main" data-note-key="m16"><div class="slidehead"><div class="eyebrow">Declarative boundary</div><h2>The DSL declares <span class="accent">WHAT language / policy we want</span><br/>the planner resolves HOW to assemble it</h2></div><div class="decisionrule"><div><b>.wistdialect</b><span>features · exclusions · backends · optimizer intent · policy</span></div><div><b>planner</b><span>dependencies · providers · ordering · executable routes</span></div></div></section>
<section class="slide stack" data-kind="main" data-note-key="m17"><div class="slidehead"><div class="eyebrow">You are here</div><h2>We can now choose a language. Next: turn that choice into a compiler.</h2></div><div class="mapflow"><div>MODULE ECOSYSTEM</div><i>↓</i><div class="on">DIALECT / CONFIG</div><i>↓</i><div>PLANNER</div><i>↓</i><div>CONCRETE PIPELINE</div><i>↓</i><div>BACKEND</div></div></section>
`);
