document.getElementById('deck').insertAdjacentHTML('beforeend', String.raw`
<section class="slide center" data-kind="main" data-note-key="m40"><div class="slidehead"><div class="eyebrow">Act 5 · The deeper composition problem</div><h2>Structural routing is not the end.<br/><span class="accent">Components also know things.</span></h2></div><p class="bigq">Once independent components exist, semantic knowledge becomes the next integration surface.</p></section>
<section class="slide two" data-kind="main" data-note-key="m41"><div class="slidehead"><div class="eyebrow">Back to our two developers</div><h2>A refinement producer may know something the bounds checker can use</h2></div><div class="panel"><h3>Developer A</h3><p>refinement / range producer derives<br/><code>0 ≤ i &lt; n</code></p></div><div class="panel"><h3>Developer B</h3><p>bounds checker asks<br/>“is this access safe?”</p></div><p class="caption span2 centertext"><span class="boundary hypothesis">HYPOTHETICAL / PROPOSED</span> bridge example; not current UT behavior.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m42"><div class="slidehead"><div class="eyebrow">Naive integration</div><h2>Producer × consumer wiring does not scale</h2></div><div class="cards3"><div class="panel"><h3>Producers</h3><p>types<br/>ranges<br/>shapes<br/>ownership<br/>effects</p></div><div class="panel"><h3>Consumers</h3><p>safety<br/>optimizer<br/>vectorizer<br/>IDE<br/>backend</p></div><div class="panel broken"><h3>Pairwise glue</h3><p class="bigq">N × M</p></div></div></section>
<section class="slide center" data-kind="main" data-note-key="m43"><div class="slidehead"><div class="eyebrow">Design target</div><h2>Add a semantic producer.<br/><span class="accent">Change zero existing consumers.</span></h2></div><p class="memory">producer independence as a falsifiable criterion</p></section>
<section class="slide stack" data-kind="main" data-note-key="m44"><div class="slidehead"><div class="eyebrow">The bridge</div><h2>Stable semantic contracts sit between producers and consumers</h2></div><div class="ownerflow"><div class="role"><b>producer</b><span>derives knowledge</span></div><i>→</i><div class="role good"><b>semantic contract</b><span>shared query vocabulary</span></div><i>→</i><div class="role"><b>consumer</b><span>asks what it needs</span></div></div><p class="caption centertext"><span class="boundary hypothesis">RESEARCH HYPOTHESIS</span> not a claim about current UT implementation.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m45"><div class="slidehead"><div class="eyebrow">Concrete semantic story</div><h2>Independent facts can meet at one shared obligation rule</h2></div><div class="ownerflow"><div class="role"><b>RangeAnalysis</b><span>0 ≤ i ≤ 7</span></div><i>+</i><div class="role"><b>Shape / Extent</b><span>length(a) = 10</span></div><i>→</i><div class="role good"><b>Contract rule</b><span>prove 0 ≤ i &lt; length(a)</span></div><i>→</i><div class="role"><b>BoundsLowering</b><span>SafeIndex discharged → omit check</span></div></div><p class="caption centertext"><span class="boundary hypothesis">HYPOTHETICAL / PROPOSED</span> The shared rule combines independent producer facts; neither producer needs a private API to the consumer.</p></section>
<section class="slide two" data-kind="main" data-note-key="m46"><div class="slidehead"><div class="eyebrow">Authority boundary</div><h2>Current UT is the demo vehicle.<br/>The semantic substrate is the design target.</h2></div><div class="panel currentbox"><span class="boundary current">CURRENT UT</span><p>modules · dialect config · dependency/provider resolution · artifact routes · frozen plans</p></div><div class="panel proposedbox"><span class="boundary hypothesis">RESEARCH / PROPOSED</span><p>judgements · evidence/validity · semantic obligations · generalized upward projection</p></div></section>
`);
