document.getElementById('deck').insertAdjacentHTML('beforeend', String.raw`
<section class="slide center" data-kind="main" data-note-key="m1"><div class="slidehead"><div class="eyebrow">LangDev 2026 · Extensible Programming on .NET</div><h2>Build the Language,<br/><span class="accent">Then Make the Abstractions Disappear</span></h2></div><div class="hero"><p class="bigq">What if a new type system, array feature or backend did not have to become another permanent edit to one compiler?</p><p class="memory">First build the mental model. Then earn the research layer.</p></div></section>
<section class="slide stack" data-kind="main" data-note-key="m2"><div class="slidehead"><div class="eyebrow">Act 1 · Why extensibility?</div><h2>A small language rarely stays small</h2></div><div class="growth"><span>arithmetic</span><i>→</i><span>variables</span><i>→</i><span>scopes</span><i>→</i><span>types</span><i>→</i><span>arrays</span><i>→</i><span>functions</span><i>→</i><span>effects</span><i>→</i><span>backends</span></div><p class="bigq centertext">Every new capability expands the semantic surface.</p></section>
<section class="slide two" data-kind="main" data-note-key="m3"><div class="slidehead"><div class="eyebrow">Coupling pressure</div><h2>One feature can cross many compiler layers</h2></div><div class="layers"><span>lexer / parser</span><span>AST</span><span>type system</span><span>analyses</span><span>IR</span><span>lowering</span><span>optimizer</span><span>backend</span><span>tooling</span></div><div class="panel"><p class="bigq">Not “every feature rewrites everything”.</p><p>But monolithic evolution creates repeated cross-layer coupling pressure.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m4"><div class="slidehead"><div class="eyebrow">Strong baseline</div><h2>A normal monolithic compiler is often the right answer</h2></div><div class="panel good"><h3>One owner</h3><p>Closed language surface<br/>Known targets<br/>Stable roadmap<br/>Explicit integration</p></div><div class="panel"><p class="bigq">Extensibility is not automatically better.</p><p>We need it only when reuse, variation or independent development is worth the composition cost.</p></div></section>
<section class="slide stack" data-kind="main" data-note-key="m5"><div class="slidehead"><div class="eyebrow">Where the pressure changes</div><h2>What if we want several languages from one ecosystem?</h2></div><div class="profile-lanes"><div><b>calculator</b><span>numbers · arithmetic</span></div><div><b>pricing DSL</b><span>restricted surface · policy</span></div><div><b>general profile</b><span>variables · loops · interop · 2 backends</span></div></div><p class="bigq centertext">Now “edit one monolith” stops being the only useful unit of work.</p></section>
<section class="slide center" data-kind="main" data-note-key="m6"><div class="slidehead"><div class="eyebrow">The extensibility question</div><h2>What if language features were <span class="accent">reusable components</span><br/>instead of permanent edits to one monolith?</h2></div><div class="brick-row"><span>Arithmetic</span><span>Scopes</span><span>Types</span><span>Arrays</span><span>Calls</span><span>Optimizer</span><span>Backend</span></div></section>
<section class="slide stack" data-kind="main" data-note-key="m7"><div class="slidehead"><div class="eyebrow">Why bother?</div><h2>Reusable language components buy real options</h2></div><div class="cards4"><div class="panel"><h3>Reuse</h3><p>share infrastructure across language profiles</p></div><div class="panel"><h3>Experiment</h3><p>swap features and implementations cheaply</p></div><div class="panel"><h3>Independence</h3><p>third parties can author extensions</p></div><div class="panel"><h3>Policy</h3><p>build restricted or target-specific languages</p></div></div></section>
<section class="slide stack" data-kind="main" data-note-key="m8"><div class="slidehead"><div class="eyebrow">The price of extensibility</div><h2>Composition becomes a systems problem</h2></div><div class="mapflow"><div class="on">MODULE ECOSYSTEM</div><i>↓</i><div>DIALECT / CONFIG</div><i>↓</i><div>PLANNER</div><i>↓</i><div>CONCRETE PIPELINE</div><i>↓</i><div>BACKEND</div></div><p class="bigq centertext">The rest of the talk is about making this arrow chain trustworthy.</p></section>
`);
