document.getElementById('deck').insertAdjacentHTML('beforeend', String.raw`
<section class="slide center" data-kind="main" data-note-key="m1"><div class="slidehead"><div class="eyebrow">LangDev 2026 · Extensible Programming on .NET</div><h2>Author language pieces.<br/><span class="accent">Resolve one compiler. Keep useful meaning.</span></h2></div><div class="hero"><p class="bigq">How can independently developed language capabilities compose into concrete languages without giving up serious optimization?</p><p class="memory">AUTHOR → RESOLVE → OPTIMIZE</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m2"><div class="slidehead"><div class="eyebrow">Start from the baseline</div><h2>A monolithic compiler is often the right answer</h2></div><div class="panel good"><h3>Prefer the monolith when</h3><p>one language<br/>one owner<br/>known targets<br/>stable roadmap</p></div><div class="panel"><p class="bigq">Extensibility has a cost.</p><p>Pay it only when reuse, variation or independent ownership matters enough.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m3"><div class="slidehead"><div class="eyebrow">Why reuse gets hard</div><h2>One language capability can cross several compiler layers</h2></div><div class="layers"><span>syntax</span><span>types</span><span>analysis</span><span>IR</span><span>lowering</span><span>optimizer</span><span>backend</span><span>tooling</span></div><div class="panel"><p class="bigq">Variation rarely stays in one hook.</p><p>Copying a whole compiler for every related language duplicates the same vertical slices.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m5"><div class="slidehead"><div class="eyebrow">Reusable unit</div><h2>A language capability is authored once against published ecosystem contracts</h2></div><div class="panel good"><h3>Language capability</h3><p>may contribute syntax, typing, analysis, lowering, optimization, backend behavior or tooling</p></div><div class="panel"><p class="bigq">Reusable piece, not a complete language.</p><p>The same capability can participate in several concrete language profiles.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m7"><div class="slidehead"><div class="eyebrow">Concrete language</div><h2>Capability ≠ language profile</h2></div><div class="panel"><h3>Capability</h3><p class="bigq">Reusable authored thing</p><p>One capability can appear in many profiles.</p></div><div class="panel good"><h3>Language profile</h3><p class="bigq">Concrete composition</p><p>Selects and constrains capabilities, policy and targets for one language.</p></div><p class="caption span2 centertext">Wist's <code>.wistdialect</code> is one profile syntax; an MLIR dialect is an IR namespace / semantic extension.</p></section>
<section class="slide two" data-kind="main" data-note-key="m11"><div class="slidehead"><div class="eyebrow">Independent development</div><h2>Share contracts — not private pairwise APIs</h2></div><div class="panel"><h3>Author A</h3><p>publishes a capability against the ecosystem contract</p></div><div class="panel"><h3>Author B</h3><p>does the same without a private A↔B integration API</p></div><p class="bigq span2 centertext">A later profile may request both; declared conflicts or requirements may still reject the composition.</p><p class="caption span2 centertext"><span class="boundary analogy">PRIOR ART</span> Neverlang, MPS and MontiCore already establish modular or independently developed language composition.</p></section>
<section class="slide center" data-kind="main" data-note-key="m12"><div class="slidehead"><div class="eyebrow">Separate request from resolution</div><h2>The profile declares <span class="accent">WHAT</span> language we want.<br/>The planner resolves <span class="accent">HOW</span> to assemble it.</h2></div><div class="decisionrule"><div><b>LANGUAGE PROFILE</b><span>capabilities · exclusions · optimizer intent · policy · targets</span></div><div class="good"><b>COMPOSITION / PLANNING</b><span>dependencies · providers · conflicts · ordering · executable routes</span></div></div></section>
<section class="slide two" data-kind="main" data-note-key="m13"><div class="slidehead"><div class="eyebrow">The obvious question</div><h2>Why not just MLIR?</h2></div><div class="panel"><span class="boundary analogy">VERIFIED PRIOR ART</span><p><b>MLIR already gives us:</b><br/>dialects · interfaces / external models<br/>legality / conversion · effects<br/>pass pipelines · Transform dialect</p></div><div class="panel good"><span class="boundary target">OUR SCOPE</span><p class="bigq">Whole-language resolution.</p><p>Which capabilities, providers, conflicts, routes, ordering constraints and backends become one compiler answer?</p></div><p class="caption span2 centertext">MLIR can be part of that answer; this is a responsibility boundary, not an incapability claim.</p></section>
<section class="slide two" data-kind="main" data-note-key="m15"><div class="slidehead"><div class="eyebrow">Close the open world</div><h2>Resolve the request into one inspectable compiler plan</h2></div><div class="panel"><div class="timeline"><div><b>REQUEST</b><span>profile + policy + targets</span></div><i>→</i><div><b>RESOLVE</b><span>providers + routes</span></div><i>→</i><div class="good"><b>PLAN</b><span>known stages + targets</span></div></div></div><div class="panel currentbox"><span class="boundary current">IMPLEMENTED WITNESS</span><p><code>LanguageDefinition</code><br/>→ <code>LanguageCompiler</code><br/>→ snapshotted <code>LanguagePlan</code><br/>→ <code>LanguageRuntime</code></p></div><p class="caption span2 centertext">Global plans are prior art too; the point is the exact whole-language responsibility owned by this plan.</p></section>
<section class="slide two" data-kind="main" data-note-key="m19"><div class="slidehead"><div class="eyebrow">A real planner regression</div><h2>The cheapest reachable route can still be structurally impossible</h2></div><div class="panel broken"><h3>cost 2</h3><p><code>SourceText → middle → executable</code><br/>artifact flow conflicts with a declared hard contribution order<br/><b>reject</b></p></div><div class="panel good"><span class="boundary current">IMPLEMENTED WITNESS</span><h3>cost 10</h3><p>direct <code>SourceText → executable</code><br/>tested hard constraints hold<br/><b>select</b></p></div><div class="sourcebar"><a href="https://github.com/Misha1302/UniversalToolchain/blob/master/UniversalToolchain/UniversalToolchain.LanguageSdk.Tests/PlannerPolicyControlTests.cs" rel="noreferrer" target="_blank">Route-order regression</a></div></section>
<section class="slide center" data-kind="main" data-note-key="m20"><div class="slidehead"><div class="eyebrow">Planning rule</div><h2><span class="accent">FEASIBILITY FIRST.</span><br/>PREFERENCE SECOND.</h2></div><div class="decisionrule"><div class="good"><b>feasible plan</b><span>a plan whose declared structural requirements hold</span></div><div><b>then rank</b><span><code>Cost</code> · target policy among survivors</span></div></div><p class="caption centertext">Structural feasibility is not semantic preservation. Transformation correctness needs separate semantic evidence, proof or validation.</p></section>
<section class="slide center" data-kind="main" data-note-key="m21"><div class="slidehead"><div class="eyebrow">Freeze the composition answer</div><h2>Open ecosystem → resolved plan → repeated per-program path</h2></div><div class="mapflow horizontal"><div>AUTHOR / DISCOVER</div><i>→</i><div>RESOLVE ONCE</div><i>→</i><div class="good">PARSE · ANALYSE · COMPILE · OPTIMIZE · EXECUTE</div></div><p class="caption centertext">For this resolved plan, global discovery and whole-language replanning need not repeat. Program-specific compiler work still does.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m25"><div class="slidehead"><div class="eyebrow">Local deabstraction · current UT witness</div><h2>When legality is local, modular machinery can disappear locally</h2></div><div class="transform-demo"><div class="panel code transform-state before"><h3>Before</h3><span class="vanish">LoadEnvironment()</span><span class="vanish">Push(slot)</span><span>LoadExternal&lt;double&gt;()</span></div><div class="transform-core"><div class="transform-arrow">→</div><div class="transform-gate"><b>exact local conditions</b><span>known slot · requested type supported</span></div></div><div class="panel good code transform-state after"><h3>After</h3><span>LoadExternal&lt;double&gt;(slot)</span></div></div><p class="caption centertext"><span class="boundary current">IMPLEMENTED WITNESS</span> Three AIR operations become one typed intrinsic; unsupported types keep the original sequence.</p></section>
<section class="slide two" data-kind="main" data-note-key="m26"><div class="slidehead"><div class="eyebrow">Now change one condition</div><h2>What if legality depends on facts outside the local IR window?</h2></div><div class="panel good"><h3>Local rewrite</h3><p>pattern + nearby type/capability facts<br/>one small window<br/>fail closed when the gate is missing</p></div><div class="panel"><h3>Non-local decision</h3><p>facts across blocks, loops or components<br/>analysis / proof evidence<br/>validity may change after transforms</p></div><p class="bigq span2 centertext">The problem moves from pattern recognition to reusable semantic evidence.</p></section>
<section class="slide two" data-kind="main" data-note-key="m28"><div class="slidehead"><div class="eyebrow">Running example</div><h2>A bounds check is a non-local proof problem</h2></div><div class="panel code bigcode">for (var i = 0; i &lt; a.Length; i++)
{
    sum += a[i];
}</div><div class="panel"><p class="bigq">The access is local. The proof is not.</p><p>A peephole pass cannot infer the whole loop argument from the access alone.</p></div></section>
<section class="slide stack" data-kind="main" data-note-key="m29"><div class="slidehead"><div class="eyebrow">Evidence can have several producers</div><h2>Range knowledge and extent knowledge meet at one consumer</h2></div><div class="ownerflow"><div class="role"><b>range analysis</b><span><code>0 ≤ i &lt; N</code></span></div><i>+</i><div class="role"><b>shape / extent</b><span><code>N = Length(a)</code></span></div><i>→</i><div class="role good"><b>bounds optimizer</b><span>asks whether this access is safe</span></div></div><p class="caption centertext">The consumer should depend on the proposition it needs, not on a specific producer implementation.</p></section>
<section class="slide two" data-kind="main" data-note-key="m30"><div class="slidehead"><div class="eyebrow">Define the query contract</div><h2>A semantic query asks a typed proposition and returns more than yes/no</h2></div><div class="panel code bigcode">SafeIndex(a, i)

unsupported
unknown
established(P)
refuted(P)
contradictory</div><div class="panel"><p class="bigq">Different failures mean different things.</p><p>The transformation owns proposition <code>P</code>; producers contribute evidence through the published contract.</p></div></section>
<section class="slide stack" data-kind="main" data-note-key="m31"><div class="slidehead"><div class="eyebrow">Discharging <code>SafeIndex</code></div><h2>Range + extent are useful only when their validity assumptions still line up</h2></div><div class="timeline"><div><b>RANGE</b><span><code>0 ≤ i &lt; N</code></span></div><i>+</i><div><b>EXTENT</b><span><code>N = Length(a)</code></span></div><i>→</i><div class="good"><b>SafeIndex(a,i)</b><span>established here</span></div><i>→</i><div><b>LOWERING</b><span>check may be omitted</span></div></div><p class="caption centertext"><span class="boundary hypothesis">RESEARCH HYPOTHESIS</span> Same subject/context/revision, compatible integer/path assumptions, and no invalidating mutation, reallocation or extent change.</p></section>
<section class="slide center" data-kind="main" data-note-key="m32"><div class="slidehead"><div class="eyebrow">The independence problem returns</div><h2>Semantic producers should integrate through a published contract</h2></div><div class="mapflow horizontal"><div>INDEPENDENT PRODUCERS</div><i>→</i><div class="good">QUERY + EVIDENCE CONTRACT</div><i>→</i><div>INDEPENDENT CONSUMERS</div></div><p class="memory">Do not make every consumer learn every producer's private API.</p></section>
<section class="slide two" data-kind="main" data-note-key="m33"><div class="slidehead"><div class="eyebrow">But this is not a green field</div><h2>LLVM and MLIR already provide serious local mechanisms</h2></div><div class="panel"><span class="boundary analogy">LLVM</span><p><code>AnalysisManager</code><br/><code>PreservedAnalyses</code><br/>pass/plugin extension points</p></div><div class="panel good"><span class="boundary analogy">MLIR</span><p>interfaces + external models<br/>effects/resources<br/>data-flow + conversion legality</p></div><p class="caption span2 centertext">Generic queries and invalidation are prior art. Any shared layer must beat these mechanisms plus explicit local adapters.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m34"><div class="slidehead"><div class="eyebrow">The narrower hypothesis</div><h2>Maybe the reusable boundary is the lifecycle of semantic evidence</h2></div><div class="ownerflow"><div class="role"><b>producer</b><span>derives evidence</span></div><i>→</i><div class="role good"><b>published lifecycle</b><span>typed state · semantic identity · context/revision · assumptions · evidence</span></div><i>→</i><div class="role"><b>consumer</b><span>asks its proposition</span></div></div><p class="caption centertext"><span class="boundary hypothesis">RESEARCH HYPOTHESIS</span> The question is whether this cross-component, cross-representation lifecycle reduces coupling without weakening correctness.</p></section>
<section class="slide center" data-kind="main" data-note-key="m35"><div class="slidehead"><div class="eyebrow">Modularity is not soundness</div><h2>Add a producer. Change zero existing consumers.</h2></div><p class="memory">Useful modularity metric — not a safety theorem.</p><p class="caption centertext">Unsupported, unknown or refuted evidence cannot discharge. Current-valid evidence for both <code>P</code> and <code>¬P</code> fails closed unless an explicit trusted reconciliation rule exists.</p></section>
<section class="slide two" data-kind="main" data-note-key="m36"><div class="slidehead"><div class="eyebrow">Second semantic domain</div><h2>A write has source/operation semantics — and later lowering obligations</h2></div><div class="panel"><h3>Operation semantics</h3><p>writability · effects/resources · alias identity · volatility · atomicity · ordering / visibility</p></div><div class="panel good"><h3>Lowering / runtime</h3><p>CoreCLR GC write barrier · target atomics/fences · transaction/runtime protocol</p></div><p class="caption span2 centertext">A CoreCLR GC write barrier is a runtime/JIT lowering obligation, not a source-level writability trait.</p></section>
<section class="slide two" data-kind="main" data-note-key="m39"><div class="slidehead"><div class="eyebrow">Why validity is unavoidable</div><h2>A perfectly typed fact can become stale after a transformation</h2></div><div class="panel broken"><h3>Naked fact</h3><p><code>range(i) = [0,n)</code></p><p>Which entity?<br/>Which context?<br/>Which revision?<br/>Which assumptions?</p></div><div class="panel"><p class="bigq">The value is not enough.</p><p>Later decisions need to know whether the evidence still describes the current program.</p></div></section>
<section class="slide two" data-kind="main" data-note-key="m40"><div class="slidehead"><div class="eyebrow">Define the evidence object</div><h2>A Judgement is a proposition plus the context that makes its evidence usable</h2></div><div class="panel good"><h3>Judgement</h3><p>subject + proposition<br/>result state<br/>context / revision<br/>assumptions + evidence</p></div><div class="panel"><h3>Published ownership</h3><p>schema + version are shared<br/>a producer cannot privately redefine the consumer's proposition</p></div><p class="caption span2 centertext"><span class="boundary hypothesis">RESEARCH HYPOTHESIS</span> “Judgement” is proposed vocabulary for this lifecycle, not a novelty claim about invalidation.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m41"><div class="slidehead"><div class="eyebrow">Define the legality requirement</div><h2>An Obligation is the proposition a transformation must establish before it is legal</h2></div><div class="timeline"><div><b>TRANSFORMATION</b><span>owns proposition <code>P</code></span></div><i>→</i><div class="good"><b>OBLIGATION</b><span>current-valid suitable evidence must establish <code>P</code></span></div><i>→</i><div><b>DISCHARGE / FAIL CLOSED</b><span>producer cannot redefine the precondition</span></div><i>→</i><div><b>LEGAL CANDIDATE</b><span>then preference may rank it</span></div></div></section>
<section class="slide two" data-kind="main" data-note-key="m43"><div class="slidehead"><div class="eyebrow">Now change representation</div><h2>Representation and knowledge are two different axes</h2></div><div class="panel"><h3>representation axis</h3><p><code>a[i]</code> → semantic IR → lowered IR → target operations</p></div><div class="panel good"><h3>knowledge axis</h3><p>evidence may be transported, re-analysed or invalidated</p></div><p class="bigq span2 centertext">The node can disappear while a later decision still needs the same semantic proposition.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m45"><div class="slidehead"><div class="eyebrow">Cross-representation rule</div><h2>Every affected later-used fact must take one of three paths</h2></div><div class="cards3"><div class="panel"><h3>Transport</h3><p>project it under a justified semantic correspondence</p></div><div class="panel"><h3>Re-analyse</h3><p>derive the property again on the current representation</p></div><div class="panel broken"><h3>Invalidate</h3><p>stop it from discharging later obligations</p></div></div><p class="caption centertext">By semantic correspondence, I mean a justified relation saying which property of the old program state remains true of the new one. Refinement is a stronger directional version of that idea.</p></section>
<section class="slide stack" data-kind="main" data-note-key="m48"><div class="slidehead"><div class="eyebrow">Closest prior art sets the bar</div><h2>The ingredients already exist — in different compiler boundaries</h2></div><div class="cards3"><div class="panel"><h3>LLVM / MLIR</h3><p>analysis managers · invalidation · interfaces · effects · legality · data-flow</p></div><div class="panel"><h3>CompCert</h3><p>semantic preservation through explicit simulations</p></div><div class="panel"><h3>Validation</h3><p>translation validation · Alive2 refinement checking</p></div></div><p class="caption centertext">The research claim cannot be “queries”, “invalidation” or “correspondence”. It must be a measurable lifecycle advantage across independent components and representations.</p></section>
<section class="slide two" data-kind="main" data-note-key="m49"><div class="slidehead"><div class="eyebrow">Strongest alternative</div><h2>Maybe the shared evidence layer should not exist</h2></div><div class="panel"><p>LLVM-style analysis manager<br/>MLIR interfaces + external models<br/>domain-specific analyses<br/>explicit local adapters<br/>local invalidation / re-analysis</p></div><div class="panel good"><p class="bigq">If this solves the coupling problem with less machinery, use it.</p><p>The shared lifecycle earns its complexity only through a measurable integration or verification benefit.</p></div></section>
<section class="slide stack" data-kind="main" data-note-key="m50"><div class="slidehead"><div class="eyebrow">Primary falsifiable experiment</div><h2>Compare the shared lifecycle against that strongest local baseline</h2></div><div class="experiment-flow"><div class="experiment-intervention"><div><span>BASELINE</span><b>interfaces + local analyses / adapters</b><small>existing consumers</small></div><i>→</i><div class="good"><span>INTERVENTION</span><b>+ independent producer through shared lifecycle</b><small>same semantic contract / obligations</small></div></div><div class="experiment-arrow">↓</div><div class="experiment-controls"><div class="good"><span>POSITIVE</span><b>new producer strengthens answers with zero existing-consumer edits</b></div><div class="broken"><span>NEGATIVE</span><b>stale · contradictory · transport-invalid evidence never discharges</b></div></div><div class="metrics"><span>false discharges</span><span>consumer edits</span><span>integration edges</span><span>precision</span><span>invalidation / re-analysis cost</span><span>schema / version burden</span></div></div></section>
<section class="slide center" data-kind="main" data-note-key="m52"><div class="slidehead"><div class="eyebrow">Final synthesis</div><h2>Extensibility should disappear where it is <span class="accent">machinery</span><br/>— and survive where it is <span class="accent">meaning</span>.</h2></div><div class="cards3"><div class="panel"><h3>AUTHOR</h3><p>published-contract capabilities<br/>→ concrete profiles</p></div><div class="panel good"><h3>RESOLVE</h3><p>profile WHAT<br/>→ one structurally feasible compiler HOW</p></div><div class="panel"><h3>OPTIMIZE</h3><p>erase machinery<br/>→ keep only current-valid semantic knowledge needed later</p></div></div><p class="caption centertext">“Meaning” here is narrow: selected current-valid semantic knowledge needed by later compiler decisions, not permanent preservation of every source representation.</p></section>
`);
