document.getElementById('deck').insertAdjacentHTML('beforeend', String.raw`
<section class="slide center" data-kind="main" data-note-key="m67"><div class="slidehead"><div class="eyebrow">Final payoff</div><h2>Build the language.<br/>Resolve the ecosystem.<br/><span class="accent">Freeze the plan.</span><br/>Optimize where representations allow it.<br/>Keep meaning queryable.</h2></div><p class="memory">Resolve composition abstractions before execution; keep semantics available through transformation.</p><p class="caption">The current UT witnesses local deabstraction and cross-backend parity. The broader semantic-contract layer remains a falsifiable research hypothesis.</p></section>
<section class="slide stack" data-kind="appendix" data-note-key="a1"><div class="slidehead"><div class="eyebrow">Appendix · vocabulary</div><h2>Stable terms used in the talk</h2></div><div class="cards3"><div class="panel"><h3>Profile / Wist dialect</h3><p>configuration selecting a language surface</p></div><div class="panel"><h3>Judgement</h3><p>contextual claim + validity + evidence</p></div><div class="panel"><h3>Obligation</h3><p>goal that must hold for correctness</p></div></div></section>
<section class="slide stack" data-kind="appendix" data-note-key="a2"><div class="slidehead"><div class="eyebrow">Appendix · trust</div><h2>Evidence is part of the semantic contract</h2></div><div class="cards3"><div class="panel"><h3>Trusted provider</h3><p>accept by policy</p></div><div class="panel"><h3>Certificate</h3><p>verify compact evidence</p></div><div class="panel"><h3>Re-analysis</h3><p>derive independently</p></div></div></section>
<section class="slide stack" data-kind="appendix" data-note-key="a3"><div class="slidehead"><div class="eyebrow">Appendix · revision</div><h2>Transforms invalidate knowledge</h2></div><div class="panel"><p class="bigq">A judgement without a revision / validity story becomes stale state disguised as semantics.</p></div></section>
<section class="slide stack" data-kind="appendix" data-note-key="a4"><div class="slidehead"><div class="eyebrow">Appendix · inverse lowering</div><h2>Why universal raising fails</h2></div><div class="cards3"><div class="panel"><h3>Split</h3><p>one entity → many</p></div><div class="panel"><h3>Merge / fusion</h3><p>many → one</p></div><div class="panel"><h3>Deletion</h3><p>node disappears while meaning matters</p></div></div></section>
<section class="slide two" data-kind="appendix" data-note-key="a5"><div class="slidehead"><div class="eyebrow">Appendix · authority boundary</div><h2>What is implemented vs proposed?</h2></div><div class="panel currentbox"><span class="boundary current">CURRENT UT</span><p>dialect configuration<br/>typed feature/contribution model<br/>dependency/provider resolution<br/>artifact routes / mandatory-pass feasibility<br/>immutable LanguagePlan / PlanHash<br/>typed AIR deabstraction rewrite<br/>interpreter + CIL parity evidence</p></div><div class="panel proposedbox"><span class="boundary hypothesis">PROPOSED / RESEARCH</span><p>general semantic Judgement substrate<br/>evidence/trust policy model<br/>semantic obligations across modules<br/>general upward semantic projection<br/>O3-like policy-derived representation requirements</p></div></section>
<section class="slide stack" data-kind="appendix" data-note-key="a6"><div class="slidehead"><div class="eyebrow">Appendix · hostile Q&amp;A</div><h2>Fast answers to predictable objections</h2></div><div class="qa-grid"><div><b>Why not a normal compiler?</b><span>Use one when variation/reuse do not justify composition.</span></div><div><b>Why not plugins?</b><span>Plugin systems can define loading, lifecycle and extension APIs; loading alone does not define semantic composition, route legality or cross-component knowledge reuse.</span></div><div><b>Why not MLIR Interfaces?</b><span>They are major prior art for semantic decoupling; the hypothesis spans additional planning/validity/cross-level concerns.</span></div><div><b>Why not one solver?</b><span>Shared typed boundaries, specialized engines.</span></div></div></section>
`);
